### ISSUE TITLE
Support for iCade announced at CES

### ISSUE THREAD

**Issue by GoogleCodeExporter** [GPF/imame4all#10]
```

http://www.ionaudio.com/icade
```

Original issue reported on code.google.com by `a2...@hotmail.com` on 11 Jan 2011 at 11:23

**Comment by isedwards** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
mcharytoniuk, @nochkin, @PaxVolumi, @absane, @hunbernd, @nikkaroraa, @cocochan55, @axjs, @weixiaoyi, @mklocek, @gubi, @xata6639, @wrutkowski, @Tarek-Bohdima, @martinstoj, @maxxx, @vansteki, @s-amaral, @si1k, @icindy, @perduta, @Loopshape, @frisir, @alberrrttt, @do-adams, @kazani-351, @ew12, @zhoudaqing, @p1aton, @roxlukas, @Exigency, @marukoRoburesu, @deathmorlock, @Hadi7546, @dvvvsh, @leolujuyi, @TheButterZone, @Isabel3122, @you21979, @lksshub, @Missliss523, @Edser9, @Jcpetrucci, @z3nth10n, @VincentBounce, @yzprofile, @panamantis, @Bjporch, @pxlryw, @mikepack

**Comment by isedwards** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
ebigram, @artemmad, @spangalas, @Cicatrice, @jhonsu01, @mikeantwarajcke, @kravens, @kaloudis, @baffolobill, @noname1007, @Ovienice, @GSinatra, @pouyakary, @tekchip, @ZachGrossi, @rkohlsjr, @leokofi, @hassan8119114, @andrsnn, @EmsAkkk, @Connor-Knabe, @nazkor, @YongboZhu, @liteCarma, @assaad, @aseemrb, @larroy, @markmark1, @mbio16, @gstarcev, @satoshi-n, @dvdknaap, @vikingux, @mrX1007, @rklasen, @danielstasielak, @Hitsxx, @irfaan, @CohibAA, @riannom, @roycewilliams, @Hexcolyte, @Maziarbey, @drhus, @codyfyi, @nothingmuch, @adrianTNT, @energetictree, @yljiang, @lusiphera

**Comment by isedwards** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
rterwedo, @arowser, @adammanter, @Dontimurio, @PedroGalveias, @bill-mcgonigle, @SkillfulHacking, @BitcoinOutput, @shaynevanasperen, @GhostPunk, @sheprnd, @bryansayler, @ppm0, @gin, @Jfeesh, @ldolini, @satrum, @Eegles, @avenbreaks, @woondroo, @brownfosman5000, @VanessaKamara, @ywjung328, @RastaDollo, @drahoslove, @lyknice23, @SimonDanisch, @gatto, @Namitch59, @hezam1, @l4ckyguy, @DriPdd, @DenSamodin, @techmarketing, @e-m-m-a, @Helee88, @bkmartin, @ppachur, @Saveurian, @micheloosterhof, @KingOlaa, @gugronnier, @barpaum, @serg4kostiuk, @MRHMuc, @robsonfagundes, @richardkiss, @brokeDude2901, @shphrd, @michaelshapkin

**Comment by isedwards** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!

**Comment by isedwards** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
